config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    def index #read all
        @flats = Flat.all
        end

        def show
            @flat = Flat.find(params[:id])
        end
    
        def new
            @flat = Flat.new
          end
    
        def create
            @flat = Flat.new(flat_params)
            @flat.save
            redirect_to flats_path(@flat)
        end
          
        
        def edit
            @flat = Flat.find(params[:id])
          end
    
          def update
            @flat = Flat.find(params[:id])
            @flat.update(flat_params)
        
            redirect_to flats_path(@flat)
          end

          def destroy
            @flat = Flat.find(params[:id])
            @flat.destroy
        
            redirect_to flats_path(@flat)
          end

          private
        
          def flat_params
            params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
          end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
    <%= f.label :description%>
  <%= f.text_field :description %>
  <%= f.label :price_per_night%>
  <%= f.text_field :price_per_night %>
  <%= f.label :number_of_guests%>
  <%= f.text_field :number_of_guests %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to the list", flats_path %>

app/views/flats/index.html.erb
<div class="container">
<h1> Flats </h1>
<ul>
<% @flats.each do |flat| %>
<li>
<%= link_to flat.name, flat_path(flat) %>
<%= link_to "Edit a flat", edit_flat_path(flat) %>
<%= link_to "Delete a flat", flat_path(flat), method: :delete %>
</li>
<%end %>
</ul>
<%= link_to "Add a flat", new_flat_path %>
</div>

app/views/flats/new.html.erb
<%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
    <%= f.label :description%>
  <%= f.text_field :description %>
  <%= f.label :price_per_night%>
  <%= f.text_field :price_per_night %>
  <%= f.label :number_of_guests%>
  <%= f.text_field :number_of_guests %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to the list", flats_path %>

app/views/flats/show.html.erb
<div class="container">
<h2><%= @flat.name %></h2>
<hr>
<p><%= @flat.address %></p>
<p><%= @flat.description%></p>
<p><%= @flat.price_per_night%></p>
<p><%= @flat.number_of_guests%></p>
<hr>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>